version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Test
          command: echo Test

  docs-build:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Build docs
          command: cd doc/ && make html
      - persist_to_workspace:
          root: doc/build
          paths: html

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/build
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "dteague@wisc.edu"
            git config user.name "dteague"
      - add_ssh_keys:
          fingerprints:
            - "b4:c1:cf:42:70:34:21:f3:70:2d:dc:5a:05:5b:53:e0"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[ci skip] Updates" --dist docs/build/html
  
workflows:
  build:
    jobs:
      - test
      - docs-build
      - docs-deploy:
          requires:
            - test
            - docs-build
          filters:
            branches:
              only: master


